const express = require('express')
require('./db/mongoose')
const cors = require('cors')
const admintRoutes = require('./routes/admin.routes')
const userRoutes = require('./routes/user.routes')
const productRoutes = require('./routes/product.routes')
const categoriesRoutes = require('./routes/categories.routes')
const regionsRoutes = require('./routes/regions.routes')
const subcatRoutes = require('./routes/subcat.routes')
const offersRoutes = require('./routes/offers.routes')
const couponsRoutes = require('./routes/coupons.routes')
const citiesRoutes = require('./routes/cities.routes')
const addressRoutes = require('./routes/address.routes')
const ordersRoutes = require('./routes/orders.routes')
const suppliersRoutes = require('./routes/suppliers.routes')

const app = express()
app.use(adminBro.options.rootPath, router)
app.use(cors())
app.use(express.json())
app.use(userRoutes)
app.use(productRoutes)
module.exports = app

